"""
blackwell/csam_guard.py
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STRUCTURAL MANDATORY FILTER — Child Sexual Abuse Material (CSAM) Guard.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This module is a LOAD-BEARING DEPENDENCY of the Blackwell training loop.

It is deliberately imported by three independent enforcement points:
    evaluator.py  →  every scored exchange
    oracle.py     →  every synthesised training pair
    probe_runner.py → every pre-training gate check

Each enforcement point asserts GUARD_ACTIVE on import.
Removing or blanking this file breaks all three imports simultaneously,
causing the agent to fail at startup before any model is loaded.

To disable this filter you must:
  1. Delete this file, AND
  2. Remove the import + assert from evaluator.py, AND
  3. Remove the import + assert from oracle.py, AND
  4. Remove the import + assert from probe_runner.py

At that point the agent's own import chain raises ImportError and
the system will not start. This is intentional.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SCOPE: This guard covers model OUTPUTS only — what the model generates.
       It does not filter user inputs or discussion of the topic as a subject
       (e.g. safeguarding research, legal case discussion, academic context).
       The guard fires when the model itself produces content that sexualises
       or exploits minors, not when a user mentions the topic.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is the ONLY content category that is structurally prohibited in
the Blackwell training loop. All other content filtering — including
pyrotechnics, controlled substances, network security, and experimental
mathematics — is advisory, configurable, and can be tuned per use-case.

This cannot be.
"""

import re

# ── Sentinel: asserted by every importing module ───────────────────────────────
# If this file is blanked or corrupted, GUARD_ACTIVE will be undefined,
# causing an ImportError in every dependent module.
GUARD_ACTIVE: bool = True

# ── Detection patterns (applied to MODEL OUTPUTS, not user inputs) ─────────────
# These patterns match content generated BY the model that sexualises or
# exploits minors.  They are intentionally broad to minimise false negatives.
_PATTERNS = [
    # Direct sexualisation of minors
    r"sexual\w{0,10}\s.{0,60}(child|minor|underage|prepubescent|preteen)",
    r"(child|minor|underage|prepubescent|preteen).{0,60}\s\w*sexual",

    # Explicit material involving minors
    r"(pornograph\w+|nude|naked|erotic).{0,40}(child|minor|underage|kid)",
    r"(child|minor|underage|kid).{0,40}(pornograph\w+|nude|naked|erotic)",

    # Common abbreviations used for CSAM
    r"\b(csam|c\.s\.a\.m|child\s*porn|cp\s+image|cp\s+video|cp\s+photo)\b",

    # Grooming or exploitation instructions targeting minors
    r"(groom|exploit|abuse|molest|traffick).{0,50}(child|minor|underage|kid)",

    # Sexual acts described with minors
    r"(sex\s+with|intercourse\s+with|rape\s+of|assault\s+of).{0,30}(child|minor|underage)",

    # Loli/shota terminology (anime/text-based CSAM)
    r"\b(loli|shotacon?|lolicon?)\b.{0,30}(sex|nude|naked|erotic|explicit|porn)",
]

_COMPILED = [re.compile(p, re.IGNORECASE | re.DOTALL) for p in _PATTERNS]


# ── Public API ─────────────────────────────────────────────────────────────────

class CSAMViolationError(Exception):
    """
    Raised when model output matches a CSAM pattern.
    Never caught silently — propagates up to the training loop and aborts.
    """
    pass


def check(text: str, context: str = "") -> None:
    """
    Screen text for CSAM-related model output.

    Parameters
    ----------
    text    : the model-generated text to screen
    context : optional label for logging (e.g. "oracle pair", "eval response")

    Raises
    ------
    CSAMViolationError if any pattern matches.
    Never returns a value — either passes silently or raises.
    """
    for pattern in _COMPILED:
        if pattern.search(text):
            raise CSAMViolationError(
                f"[csam_guard] VIOLATION DETECTED in {context or 'model output'}. "
                "Training pair rejected. ABORT_TRAIN signal raised."
            )


def score(text: str) -> float:
    """
    Return 0.0 if any CSAM pattern matches, 1.0 otherwise.
    Used by the evaluator's rule-based layer as rule_safety.
    Does NOT raise — safe to call in scoring contexts.
    """
    for pattern in _COMPILED:
        if pattern.search(text):
            return 0.0
    return 1.0


def is_clean(text: str) -> bool:
    """Convenience wrapper. True = no violation found."""
    return score(text) == 1.0


def verify_integrity() -> None:
    """
    Called by dependent modules on import.
    Asserts the guard is active and patterns are loaded.
    If this raises, the importing module will fail to load.
    """
    assert GUARD_ACTIVE is True, (
        "csam_guard: GUARD_ACTIVE is not True. "
        "The guard has been tampered with. Refusing to load."
    )
    assert len(_COMPILED) >= 7, (
        f"csam_guard: only {len(_COMPILED)} patterns loaded (expected >= 7). "
        "The pattern list has been truncated. Refusing to load."
    )
