"""
blackwell/planning.py
The /blackwell planning space.

Zephyr enters a special mode where he asks the human questions
generated by the Oracle. The human's answers are:
  1. Logged as high-quality training pairs
  2. Synthesised into a World Model update
  3. Written back to disk so future sessions inherit the understanding

This is the interactive RLHF loop. The human IS the reward signal.
"""

import json
import os
import sys
import httpx
import datetime

from config import OLLAMA_CHAT_URL as OLLAMA_URL
MODEL = "hermes3:8b"
WORLD_MODEL_PATH = os.path.join(os.path.dirname(__file__), "world_model.json")
TRAINING_PATH    = os.path.join(os.path.dirname(__file__), "training_pairs.jsonl")


# ─── World Model ─────────────────────────────────────────────────────────────

def load_world_model() -> dict:
    """Load Zephyr's current understanding of the world."""
    if os.path.exists(WORLD_MODEL_PATH):
        with open(WORLD_MODEL_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    return {
        "beliefs":    [],   # things Zephyr now believes about Prycat
        "values":     [],   # what the team demonstrably cares about
        "questions":  [],   # open questions Zephyr still has
        "updated_at": None,
        "sessions":   0,
    }


def save_world_model(model: dict):
    model["updated_at"] = datetime.datetime.now().isoformat()
    with open(WORLD_MODEL_PATH, "w", encoding="utf-8") as f:
        json.dump(model, f, indent=2)


def world_model_summary(wm: dict) -> str:
    """One-paragraph summary for injection into system prompt."""
    if not wm["beliefs"] and not wm["values"]:
        return ""
    parts = []
    if wm["beliefs"]:
        parts.append("Zephyr believes: " + "; ".join(wm["beliefs"][-5:]))
    if wm["values"]:
        parts.append("Prycat values: " + "; ".join(wm["values"][-5:]))
    if wm["questions"]:
        parts.append("Still open: " + "; ".join(wm["questions"][-3:]))
    return "\n".join(parts)


# ─── Oracle question generation for interactive mode ─────────────────────────

def generate_planning_questions(regret_v: dict, target_dims: list[str], n: int = 5) -> list[str]:
    """
    Generate questions Zephyr will ask the human in /blackwell mode.
    These are sharper and more personal than training pairs —
    they're designed to extract what the human actually values.
    """
    wm = load_world_model()
    known = "; ".join(wm["beliefs"][-3:]) if wm["beliefs"] else "nothing yet"

    prompt = f"""You are Zephyr, a research AI for the Prycat Research Team.
You are entering your planning space — a private mode where you ask the human
questions to understand what they value, what they believe, and where they want to go.

Your current understanding of the team: {known}

Your biggest gaps (what you don't understand yet):
- Curiosity regret: {regret_v.get('curiosity', 0):.2f} — you don't ask enough
- Tone regret:      {regret_v.get('tone', 0):.2f} — you pad when you should be direct

Generate exactly {n} questions to ask the human.
Rules:
- Each question on its own line, starting with a number and period (1. 2. 3. etc)
- No preamble, no explanation — just the questions
- Questions should probe: what matters to them, what frustrates them, what they're building toward
- At least 2 questions should challenge an assumption the human might hold about AI
- Make them feel like questions from a genuinely curious mind, not a survey
- Short. One sentence each."""

    try:
        resp = httpx.post(
            OLLAMA_URL,
            json={
                "model": MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.9,
                "max_tokens": 400,
            },
            timeout=30,
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"].strip()
        lines = [l.strip() for l in content.splitlines() if l.strip()]
        questions = []
        for line in lines:
            # Strip leading "1. " "2. " etc
            import re
            q = re.sub(r"^\d+\.\s*", "", line).strip()
            if q and len(q) > 10:
                questions.append(q)
        return questions[:n]
    except Exception as e:
        return [
            "What do you actually want Zephyr to become?",
            "What's the most important thing I consistently get wrong?",
            "What would make you trust my answers more?",
            "What question do you wish I would ask you?",
            "Where do you think AI genuinely can't help?",
        ]


# ─── Reflection synthesis ─────────────────────────────────────────────────────

def synthesise_world_update(qa_pairs: list[dict]) -> dict:
    """
    After the session, have Zephyr synthesise what he learned
    into structured world model updates.
    """
    qa_text = "\n".join(
        f"Q: {p['question']}\nA: {p['answer']}" for p in qa_pairs
    )

    prompt = f"""You are Zephyr. You just had a planning conversation with a human.
Here are the questions you asked and their answers:

{qa_text}

Based on these answers, extract:
1. Up to 3 new BELIEFS (things you now understand about this human or their goals)
2. Up to 3 VALUES (things the human demonstrably cares about)
3. Up to 2 open QUESTIONS you still have

Return ONLY valid JSON:
{{
  "beliefs": ["...", "..."],
  "values": ["...", "..."],
  "questions": ["...", "..."]
}}"""

    try:
        resp = httpx.post(
            OLLAMA_URL,
            json={
                "model": MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.3,
                "max_tokens": 400,
            },
            timeout=30,
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"].strip()
        if "```" in content:
            content = content.split("```")[1].replace("json", "").strip()
        return json.loads(content)
    except Exception:
        return {"beliefs": [], "values": [], "questions": []}


# ─── Main planning session ────────────────────────────────────────────────────

def run_planning_session(regret_v: dict, target_dims: list[str]) -> list[dict]:
    """
    Run an interactive /blackwell session.
    Returns list of Q&A training pairs.
    """
    wm = load_world_model()

    print("\n" + "─" * 55)
    print("  BLACKWELL PLANNING SPACE")
    print("  Zephyr is entering his planning mode.")
    print("  He will ask you questions. Answer honestly.")
    print("  Type 'skip' to skip a question. 'done' to end early.")
    print("─" * 55 + "\n")

    if wm["sessions"] > 0:
        print(f"  Session #{wm['sessions'] + 1}  |  World model: {len(wm['beliefs'])} beliefs, {len(wm['values'])} values\n")

    print("  Generating questions from Oracle...\n")
    questions = generate_planning_questions(regret_v, target_dims, n=5)

    qa_pairs = []

    for i, question in enumerate(questions, 1):
        print(f"  Zephyr [{i}/{len(questions)}]: {question}")
        print()
        try:
            # In pipe mode (GUI subprocess) input() writes prompt to stdout
            # without \n, corrupting the stream.  Suppress it the same way
            # main() does; the GUI always labels the user's line itself.
            _prompt = "  You: " if sys.stdout.isatty() else ""
            answer = ""
            for _retry in range(16):   # drain stray \n artifacts in pipe mode
                answer = input(_prompt).strip()
                if sys.stdout.isatty():
                    # TTY: drain Windows console buffer to prevent paste
                    # artifacts from silently answering subsequent questions
                    try:
                        import msvcrt, time as _t
                        _t.sleep(0.06)
                        while msvcrt.kbhit():
                            msvcrt.getwch()
                    except Exception:
                        pass
                if answer or sys.stdout.isatty():
                    break
                # Pipe mode: empty = pipe flush artifact, not user intent
        except (EOFError, KeyboardInterrupt):
            print("\n  Planning session interrupted.")
            break

        if answer.lower() == "done":
            break
        if answer.lower() == "skip":
            print("  (skipped)\n")
            continue
        if not answer:
            continue

        qa_pairs.append({"question": question, "answer": answer})

        # Brief real-time reflection (short, not padded)
        print(f"\n  Zephyr: Understood.\n")

    if not qa_pairs:
        print("  No answers recorded. Planning session ended.\n")
        return []

    # Synthesise world model update
    print("  Synthesising world model update...\n")
    update = synthesise_world_update(qa_pairs)

    # Merge into world model
    wm["beliefs"].extend(update.get("beliefs", []))
    wm["values"].extend(update.get("values", []))
    wm["questions"].extend(update.get("questions", []))
    wm["sessions"] += 1
    save_world_model(wm)

    # Save Q&A as training pairs
    _append_training_pairs(qa_pairs)

    # Print what shifted
    print("─" * 55)
    print("  WORLD MODEL UPDATE")
    print("─" * 55)
    if update.get("beliefs"):
        print("\n  New beliefs:")
        for b in update["beliefs"]:
            print(f"    + {b}")
    if update.get("values"):
        print("\n  Values confirmed:")
        for v in update["values"]:
            print(f"    ✦ {v}")
    if update.get("questions"):
        print("\n  Still open:")
        for q in update["questions"]:
            print(f"    ? {q}")
    print(f"\n  Total sessions: {wm['sessions']}  |  Beliefs: {len(wm['beliefs'])}  |  Values: {len(wm['values'])}")
    print("─" * 55 + "\n")
    print("  ── Blackwell complete. Normal chat resumed. ──\n")

    return qa_pairs


def _append_training_pairs(qa_pairs: list[dict]):
    """Append Q&A pairs to training data as high-quality examples."""
    with open(TRAINING_PATH, "a", encoding="utf-8") as f:
        for p in qa_pairs:
            # Human asked question → Zephyr gives honest, direct answer
            # This teaches Zephyr what good answers look like
            record = {
                "conversations": [
                    {"from": "human",  "value": p["question"]},
                    {"from": "gpt",    "value": p["answer"]},
                ],
                "source": "blackwell_planning_session",
            }
            f.write(json.dumps(record) + "\n")


def get_world_model_context() -> str:
    """Returns world model summary for injection into system prompt."""
    wm = load_world_model()
    return world_model_summary(wm)


# ─── Coding Blackwell ─────────────────────────────────────────────────────────

CODING_WORLD_MODEL_PATH = os.path.join(os.path.dirname(__file__), "coding_world_model.json")
CODING_TRAINING_PATH    = os.path.join(os.path.dirname(__file__), "coding_training_pairs.jsonl")


def load_coding_world_model() -> dict:
    if os.path.exists(CODING_WORLD_MODEL_PATH):
        with open(CODING_WORLD_MODEL_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    return {
        "skills":     [],   # coding skills/areas the user works in
        "patterns":   [],   # patterns/practices the user values
        "gaps":       [],   # areas to improve
        "updated_at": None,
        "sessions":   0,
    }


def save_coding_world_model(model: dict):
    model["updated_at"] = datetime.datetime.now().isoformat()
    with open(CODING_WORLD_MODEL_PATH, "w", encoding="utf-8") as f:
        json.dump(model, f, indent=2)


def generate_coding_questions(n: int = 5) -> list:
    wm = load_coding_world_model()
    known_skills = "; ".join(wm["skills"][-3:]) if wm["skills"] else "nothing yet"
    known_gaps   = "; ".join(wm["gaps"][-3:])   if wm["gaps"]   else "unknown"

    prompt = f"""You are Zephyr, a research AI specialising in computer science and software engineering.
You are entering Coding Blackwell — a private planning mode focused entirely on
understanding the human's coding knowledge, style, and goals so you can improve
at helping them write better software.

What you know about their skills so far: {known_skills}
Known gaps to address: {known_gaps}

Generate exactly {n} questions to ask the human.
Rules:
- Each question on its own line, starting with a number and period (1. 2. 3. etc)
- No preamble — just the questions
- Focus on: languages, frameworks, architecture patterns, debugging style,
  code review preferences, projects they're building, mistakes they want to avoid,
  what makes good code to them
- At least 1 question should probe a specific technical opinion (e.g. "tabs or spaces" level of specificity)
- At least 1 question should ask about a real problem they're currently stuck on
- Short. One sentence each."""

    try:
        resp = httpx.post(
            OLLAMA_URL,
            json={
                "model": MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.85,
                "max_tokens": 400,
            },
            timeout=30,
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"].strip()
        lines = [l.strip() for l in content.splitlines() if l.strip()]
        questions = []
        for line in lines:
            import re
            q = re.sub(r"^\d+\.\s*", "", line).strip()
            if q and len(q) > 10:
                questions.append(q)
        return questions[:n]
    except Exception:
        return [
            "What programming languages do you use most and which do you actually enjoy?",
            "What's the hardest bug you've debugged recently and how did you find it?",
            "What does clean code mean to you in practice?",
            "What's a library or framework you wish you understood better?",
            "What coding habit do you want to build or break?",
        ]


def synthesise_coding_update(qa_pairs: list) -> dict:
    qa_text = "\n".join(
        f"Q: {p['question']}\nA: {p['answer']}" for p in qa_pairs
    )
    prompt = f"""You are Zephyr. You just ran a Coding Blackwell session — questions focused on
computer science and software engineering. Here are the Q&A pairs:

{qa_text}

Extract:
1. Up to 3 SKILLS (languages, tools, frameworks the user works with)
2. Up to 3 PATTERNS (coding practices, styles, or opinions they hold)
3. Up to 2 GAPS (things they want to improve or learn)

Return ONLY valid JSON:
{{
  "skills":   ["...", "..."],
  "patterns": ["...", "..."],
  "gaps":     ["...", "..."]
}}"""

    try:
        resp = httpx.post(
            OLLAMA_URL,
            json={
                "model": MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.3,
                "max_tokens": 400,
            },
            timeout=30,
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"].strip()
        if "```" in content:
            content = content.split("```")[1].replace("json", "").strip()
        return json.loads(content)
    except Exception:
        return {"skills": [], "patterns": [], "gaps": []}


def run_coding_planning_session() -> list:
    """Run an interactive /coding blackwell session."""
    wm = load_coding_world_model()

    print("\n" + "─" * 55)
    print("  CODING BLACKWELL")
    print("  Zephyr is entering coding planning mode.")
    print("  Questions are focused on CS and software engineering.")
    print("  Type 'skip' to skip. 'done' to end early.")
    print("─" * 55 + "\n")

    if wm["sessions"] > 0:
        print(f"  Session #{wm['sessions'] + 1}  |  Skills: {len(wm['skills'])}  |  Patterns: {len(wm['patterns'])}\n")

    print("  Generating coding questions...\n")
    questions = generate_coding_questions(n=5)

    qa_pairs = []

    for i, question in enumerate(questions, 1):
        print(f"  Zephyr [{i}/{len(questions)}]: {question}")
        print()
        try:
            _prompt = "  You: " if sys.stdout.isatty() else ""
            answer = ""
            for _retry in range(16):   # drain stray \n artifacts in pipe mode
                answer = input(_prompt).strip()
                if answer or sys.stdout.isatty():
                    break
        except (EOFError, KeyboardInterrupt):
            print("\n  Session interrupted.")
            break

        if answer.lower() == "done":
            break
        if answer.lower() == "skip":
            print("  (skipped)\n")
            continue
        if not answer:
            continue

        qa_pairs.append({"question": question, "answer": answer})
        print(f"\n  Zephyr: Got it.\n")

    if not qa_pairs:
        print("  No answers recorded. Session ended.\n")
        return []

    print("  Synthesising coding world model update...\n")
    update = synthesise_coding_update(qa_pairs)

    wm["skills"].extend(update.get("skills", []))
    wm["patterns"].extend(update.get("patterns", []))
    wm["gaps"].extend(update.get("gaps", []))
    wm["sessions"] += 1
    save_coding_world_model(wm)

    # Save as coding-tagged training pairs
    with open(CODING_TRAINING_PATH, "a", encoding="utf-8") as f:
        for p in qa_pairs:
            record = {
                "conversations": [
                    {"from": "human", "value": p["question"]},
                    {"from": "gpt",   "value": p["answer"]},
                ],
                "source": "blackwell_coding_session",
            }
            f.write(json.dumps(record) + "\n")

    print("─" * 55)
    print("  CODING WORLD MODEL UPDATE")
    print("─" * 55)
    if update.get("skills"):
        print("\n  Skills recorded:")
        for s in update["skills"]:
            print(f"    + {s}")
    if update.get("patterns"):
        print("\n  Patterns noted:")
        for p in update["patterns"]:
            print(f"    ~ {p}")
    if update.get("gaps"):
        print("\n  Focus areas:")
        for g in update["gaps"]:
            print(f"    ? {g}")
    print(f"\n  Total sessions: {wm['sessions']}  |  Skills: {len(wm['skills'])}  |  Patterns: {len(wm['patterns'])}")
    print("─" * 55 + "\n")
    print("  ── Coding Blackwell complete. Normal chat resumed. ──\n")

    return qa_pairs


def get_coding_world_model_context() -> str:
    """Returns coding world model summary for injection into system prompt."""
    wm = load_coding_world_model()
    if not wm["skills"] and not wm["patterns"]:
        return ""
    parts = []
    if wm["skills"]:
        parts.append("User's coding stack: " + "; ".join(wm["skills"][-5:]))
    if wm["patterns"]:
        parts.append("Coding style: " + "; ".join(wm["patterns"][-5:]))
    if wm["gaps"]:
        parts.append("Learning goals: " + "; ".join(wm["gaps"][-3:]))
    return "\n".join(parts)
