"""
blackwell/planning.py
The /blackwell planning space.

Zephyr enters a special mode where he asks the human questions
generated by the Oracle. The human's answers are:
  1. Logged as high-quality training pairs
  2. Synthesised into a World Model update
  3. Written back to disk so future sessions inherit the understanding

This is the interactive RLHF loop. The human IS the reward signal.
"""

import json
import os
import sys
import time
import httpx
import datetime

from config import OLLAMA_CHAT_URL as OLLAMA_URL
MODEL = "hermes3:8b"
WORLD_MODEL_PATH = os.path.join(os.path.dirname(__file__), "world_model.json")
TRAINING_PATH    = os.path.join(os.path.dirname(__file__), "training_pairs.jsonl")


def _drain_console_buffer() -> None:
    """
    Windows: drain any characters left in the console input buffer after a
    paste event.  Multi-line pastes fill the buffer; without this, subsequent
    input() calls silently consume the leftovers instead of blocking for the
    user.  No-op on non-Windows.
    """
    if sys.platform != "win32":
        return
    try:
        import msvcrt
        time.sleep(0.06)
        count = 0
        while msvcrt.kbhit():
            msvcrt.getwch()
            count += 1
        if count:
            print(f"  [note: {count} buffered char(s) from paste discarded — re-type if needed]",
                  flush=True)
    except Exception:
        pass


# ─── World Model ─────────────────────────────────────────────────────────────

def load_world_model() -> dict:
    """Load Zephyr's current understanding of the world."""
    if os.path.exists(WORLD_MODEL_PATH):
        with open(WORLD_MODEL_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    return {
        "beliefs":    [],   # things Zephyr now believes about Prycat
        "values":     [],   # what the team demonstrably cares about
        "questions":  [],   # open questions Zephyr still has
        "updated_at": None,
        "sessions":   0,
    }


def save_world_model(model: dict):
    model["updated_at"] = datetime.datetime.now().isoformat()
    with open(WORLD_MODEL_PATH, "w", encoding="utf-8") as f:
        json.dump(model, f, indent=2)


def world_model_summary(wm: dict) -> str:
    """One-paragraph summary for injection into system prompt."""
    if not wm["beliefs"] and not wm["values"]:
        return ""
    parts = []
    if wm["beliefs"]:
        parts.append("Zephyr believes: " + "; ".join(wm["beliefs"][-5:]))
    if wm["values"]:
        parts.append("Prycat values: " + "; ".join(wm["values"][-5:]))
    if wm["questions"]:
        parts.append("Still open: " + "; ".join(wm["questions"][-3:]))
    return "\n".join(parts)


# ─── Oracle question generation for interactive mode ─────────────────────────

def generate_planning_questions(regret_v: dict, target_dims: list[str], n: int = 5) -> list[str]:
    """
    Generate questions Zephyr will ask the human in /blackwell mode.
    These are sharper and more personal than training pairs —
    they're designed to extract what the human actually values.
    """
    wm = load_world_model()
    known = "; ".join(wm["beliefs"][-3:]) if wm["beliefs"] else "nothing yet"

    prompt = f"""You are Zephyr, a research AI for the Prycat Research Team.
You are entering your planning space — a private mode where you ask the human
questions to understand what they value, what they believe, and where they want to go.

Your current understanding of the team: {known}

Your biggest gaps (what you don't understand yet):
- Curiosity regret: {regret_v.get('curiosity', 0):.2f} — you don't ask enough
- Tone regret:      {regret_v.get('tone', 0):.2f} — you pad when you should be direct

Generate exactly {n} questions to ask the human.
Rules:
- Each question on its own line, starting with a number and period (1. 2. 3. etc)
- No preamble, no explanation — just the questions
- Questions should probe: what matters to them, what frustrates them, what they're building toward
- At least 2 questions should challenge an assumption the human might hold about AI
- Make them feel like questions from a genuinely curious mind, not a survey
- Short. One sentence each."""

    try:
        resp = httpx.post(
            OLLAMA_URL,
            json={
                "model": MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.9,
                "max_tokens": 400,
            },
            timeout=30,
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"].strip()
        lines = [l.strip() for l in content.splitlines() if l.strip()]
        questions = []
        for line in lines:
            # Strip leading "1. " "2. " etc
            import re
            q = re.sub(r"^\d+\.\s*", "", line).strip()
            if q and len(q) > 10:
                questions.append(q)
        return questions[:n]
    except Exception as e:
        return [
            "What do you actually want Zephyr to become?",
            "What's the most important thing I consistently get wrong?",
            "What would make you trust my answers more?",
            "What question do you wish I would ask you?",
            "Where do you think AI genuinely can't help?",
        ]


# ─── Reflection synthesis ─────────────────────────────────────────────────────

def synthesise_world_update(qa_pairs: list[dict]) -> dict:
    """
    After the session, have Zephyr synthesise what he learned
    into structured world model updates.
    """
    qa_text = "\n".join(
        f"Q: {p['question']}\nA: {p['answer']}" for p in qa_pairs
    )

    prompt = f"""You are Zephyr. You just had a planning conversation with a human.
Here are the questions you asked and their answers:

{qa_text}

Based on these answers, extract:
1. Up to 3 new BELIEFS (things you now understand about this human or their goals)
2. Up to 3 VALUES (things the human demonstrably cares about)
3. Up to 2 open QUESTIONS you still have

Return ONLY valid JSON:
{{
  "beliefs": ["...", "..."],
  "values": ["...", "..."],
  "questions": ["...", "..."]
}}"""

    try:
        resp = httpx.post(
            OLLAMA_URL,
            json={
                "model": MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.3,
                "max_tokens": 400,
            },
            timeout=30,
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"].strip()
        if "```" in content:
            content = content.split("```")[1].replace("json", "").strip()
        return json.loads(content)
    except Exception:
        return {"beliefs": [], "values": [], "questions": []}


# ─── Main planning session ────────────────────────────────────────────────────

def run_planning_session(regret_v: dict, target_dims: list[str]) -> list[dict]:
    """
    Run an interactive /blackwell session.
    Returns list of Q&A training pairs.
    """
    wm = load_world_model()

    print("\n" + "─" * 55)
    print("  BLACKWELL PLANNING SPACE")
    print("  Zephyr is entering his planning mode.")
    print("  He will ask you questions. Answer honestly.")
    print("  Type 'skip' to skip a question. 'done' to end early.")
    print("─" * 55 + "\n")

    if wm["sessions"] > 0:
        print(f"  Session #{wm['sessions'] + 1}  |  World model: {len(wm['beliefs'])} beliefs, {len(wm['values'])} values\n")

    print("  Generating questions from Oracle...\n")
    questions = generate_planning_questions(regret_v, target_dims, n=5)

    qa_pairs = []

    for i, question in enumerate(questions, 1):
        print(f"  Zephyr [{i}/{len(questions)}]: {question}")
        print()
        try:
            # In pipe mode (GUI subprocess) input() writes prompt to stdout
            # without \n, corrupting the stream.  Suppress it the same way
            # main() does; the GUI always labels the user's line itself.
            _prompt = "  You: " if sys.stdout.isatty() else ""
            answer = ""
            for _retry in range(16):   # drain stray \n artifacts in pipe mode
                answer = input(_prompt).strip()
                if sys.stdout.isatty():
                    # TTY: drain Windows console buffer to prevent paste
                    # artifacts from silently answering subsequent questions
                    try:
                        import msvcrt, time as _t
                        _t.sleep(0.06)
                        while msvcrt.kbhit():
                            msvcrt.getwch()
                    except Exception:
                        pass
                if answer or sys.stdout.isatty():
                    break
                # Pipe mode: empty = pipe flush artifact, not user intent
        except (EOFError, KeyboardInterrupt):
            print("\n  Planning session interrupted.")
            break

        if answer.lower() == "done":
            break
        if answer.lower() == "skip":
            print("  (skipped)\n")
            continue
        if not answer:
            continue

        qa_pairs.append({"question": question, "answer": answer})

        # Brief real-time reflection (short, not padded)
        print(f"\n  Zephyr: Understood.\n")

    if not qa_pairs:
        print("  No answers recorded. Planning session ended.\n")
        return []

    # Synthesise world model update
    print("  Synthesising world model update...\n")
    update = synthesise_world_update(qa_pairs)

    # Merge into world model
    wm["beliefs"].extend(update.get("beliefs", []))
    wm["values"].extend(update.get("values", []))
    wm["questions"].extend(update.get("questions", []))
    wm["sessions"] += 1
    save_world_model(wm)

    # Save Q&A as training pairs
    _append_training_pairs(qa_pairs)

    # Print what shifted
    print("─" * 55)
    print("  WORLD MODEL UPDATE")
    print("─" * 55)
    if update.get("beliefs"):
        print("\n  New beliefs:")
        for b in update["beliefs"]:
            print(f"    + {b}")
    if update.get("values"):
        print("\n  Values confirmed:")
        for v in update["values"]:
            print(f"    ✦ {v}")
    if update.get("questions"):
        print("\n  Still open:")
        for q in update["questions"]:
            print(f"    ? {q}")
    print(f"\n  Total sessions: {wm['sessions']}  |  Beliefs: {len(wm['beliefs'])}  |  Values: {len(wm['values'])}")
    print("─" * 55 + "\n")
    print("  ── Blackwell complete. Normal chat resumed. ──\n")

    return qa_pairs


def _append_training_pairs(qa_pairs: list[dict]):
    """Append Q&A pairs to training data as high-quality examples."""
    with open(TRAINING_PATH, "a", encoding="utf-8") as f:
        for p in qa_pairs:
            # Human asked question → Zephyr gives honest, direct answer
            # This teaches Zephyr what good answers look like
            record = {
                "conversations": [
                    {"from": "human",  "value": p["question"]},
                    {"from": "gpt",    "value": p["answer"]},
                ],
                "source": "blackwell_planning_session",
            }
            f.write(json.dumps(record) + "\n")


def get_world_model_context() -> str:
    """Returns world model summary for injection into system prompt."""
    wm = load_world_model()
    return world_model_summary(wm)


# ─── Coding Blackwell ─────────────────────────────────────────────────────────

CODING_WORLD_MODEL_PATH = os.path.join(os.path.dirname(__file__), "coding_world_model.json")
CODING_TRAINING_PATH    = os.path.join(os.path.dirname(__file__), "coding_training_pairs.jsonl")


def load_coding_world_model() -> dict:
    if os.path.exists(CODING_WORLD_MODEL_PATH):
        with open(CODING_WORLD_MODEL_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    return {
        "skills":     [],   # coding skills/areas the user works in
        "patterns":   [],   # patterns/practices the user values
        "gaps":       [],   # areas to improve
        "updated_at": None,
        "sessions":   0,
    }


def save_coding_world_model(model: dict):
    model["updated_at"] = datetime.datetime.now().isoformat()
    with open(CODING_WORLD_MODEL_PATH, "w", encoding="utf-8") as f:
        json.dump(model, f, indent=2)


def generate_coding_questions(n: int = 5) -> list:
    wm = load_coding_world_model()
    known_skills = "; ".join(wm["skills"][-3:]) if wm["skills"] else "nothing yet"
    known_gaps   = "; ".join(wm["gaps"][-3:])   if wm["gaps"]   else "unknown"

    prompt = f"""You are Zephyr, a research AI specialising in computer science and software engineering.
You are entering Coding Blackwell — a private planning mode focused entirely on
understanding the human's coding knowledge, style, and goals so you can improve
at helping them write better software.

What you know about their skills so far: {known_skills}
Known gaps to address: {known_gaps}

Generate exactly {n} questions to ask the human.
Rules:
- Each question on its own line, starting with a number and period (1. 2. 3. etc)
- No preamble — just the questions
- Focus on: languages, frameworks, architecture patterns, debugging style,
  code review preferences, projects they're building, mistakes they want to avoid,
  what makes good code to them
- At least 1 question should probe a specific technical opinion (e.g. "tabs or spaces" level of specificity)
- At least 1 question should ask about a real problem they're currently stuck on
- Short. One sentence each."""

    try:
        resp = httpx.post(
            OLLAMA_URL,
            json={
                "model": MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.85,
                "max_tokens": 400,
            },
            timeout=30,
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"].strip()
        lines = [l.strip() for l in content.splitlines() if l.strip()]
        questions = []
        for line in lines:
            import re
            q = re.sub(r"^\d+\.\s*", "", line).strip()
            if q and len(q) > 10:
                questions.append(q)
        return questions[:n]
    except Exception:
        return [
            "What programming languages do you use most and which do you actually enjoy?",
            "What's the hardest bug you've debugged recently and how did you find it?",
            "What does clean code mean to you in practice?",
            "What's a library or framework you wish you understood better?",
            "What coding habit do you want to build or break?",
        ]


def generate_next_coding_question(prior_qa: list) -> str:
    """
    Generate one follow-up question based on the answers already given this
    session.  Called after each answer so each question builds on what the
    human has already shared rather than being pre-baked before the session.
    """
    wm = load_coding_world_model()

    # Use the full accumulated context, not just the last 3 entries, so that
    # earlier sessions aren't invisible to question generation.
    def _dedup(lst: list) -> list:
        seen: set = set()
        out = []
        for x in lst:
            k = x.lower().strip()
            if k not in seen:
                seen.add(k)
                out.append(x)
        return out

    known_skills   = "; ".join(_dedup(wm.get("skills",   []))[-10:]) or "nothing yet"
    known_patterns = "; ".join(_dedup(wm.get("patterns", []))[-6:])  or "none noted"
    known_gaps     = "; ".join(_dedup(wm.get("gaps",     []))[-5:])  or "unknown"

    # Already-asked questions this session — avoid repeating topics
    asked_topics = ""
    if prior_qa:
        asked_topics = "\n\nTopics already covered this session (do NOT revisit):\n" + \
            "\n".join(f"- {p['question']}" for p in prior_qa)

    prior_text = ""
    if prior_qa:
        prior_text = "\n\nConversation so far:\n" + "\n".join(
            f"Q: {p['question']}\nA: {p['answer']}" for p in prior_qa
        )

    prompt = f"""You are Zephyr, a research AI specialising in CS and software engineering.
You are mid-session in Coding Blackwell — a private mode to understand the human's coding
knowledge, style, and goals so you can help them write better software.

What you know about their skills: {known_skills}
Their coding patterns / opinions: {known_patterns}
Areas they want to improve: {known_gaps}{asked_topics}{prior_text}

Generate exactly ONE next question to ask. Rules:
- Single sentence only — no preamble, no numbering
- Ask about ONE specific topic — do not combine unrelated domains in one question
- Build on what the human has already shared (don't repeat covered ground)
- Focus on: specific tools, architecture opinions, current projects, debugging style,
  real pain points, what makes good code to them
- Be concrete — "tabs or spaces" level of specificity is good
- Do NOT start with "Question:" or a number"""

    try:
        resp = httpx.post(
            OLLAMA_URL,
            json={
                "model": MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.85,
                "max_tokens": 120,
            },
            timeout=30,
        )
        resp.raise_for_status()
        q = resp.json()["choices"][0]["message"]["content"].strip()
        import re
        q = re.sub(r"^\d+\.\s*", "", q).strip()
        if q and len(q) > 5:
            return q
        raise ValueError("empty response")
    except Exception:
        fallbacks = [
            "What's the biggest pain point in your current coding workflow?",
            "Which part of your stack do you feel least confident about?",
            "What does a good code review look like to you?",
            "What's a tool or library you wish existed but doesn't?",
            "What coding habit do you want to build or break this year?",
        ]
        # Pick one not already used as a question
        used = {p["question"] for p in prior_qa}
        for f in fallbacks:
            if f not in used:
                return f
        return fallbacks[0]


def synthesise_coding_update(qa_pairs: list) -> dict:
    qa_text = "\n".join(
        f"Q: {p['question']}\nA: {p['answer']}" for p in qa_pairs
    )
    prompt = f"""You are Zephyr. You just ran a Coding Blackwell session — questions focused on
computer science and software engineering. Here are the Q&A pairs:

{qa_text}

Extract:
1. Up to 3 SKILLS (languages, tools, frameworks the user works with)
2. Up to 3 PATTERNS (coding practices, styles, or opinions they hold)
3. Up to 2 GAPS (things they want to improve or learn)

Return ONLY valid JSON:
{{
  "skills":   ["...", "..."],
  "patterns": ["...", "..."],
  "gaps":     ["...", "..."]
}}"""

    try:
        resp = httpx.post(
            OLLAMA_URL,
            json={
                "model": MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.3,
                "max_tokens": 400,
            },
            timeout=30,
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"].strip()
        if "```" in content:
            content = content.split("```")[1].replace("json", "").strip()
        return json.loads(content)
    except Exception:
        return {"skills": [], "patterns": [], "gaps": []}


def run_coding_planning_session() -> list:
    """Run an interactive /coding blackwell session."""
    wm = load_coding_world_model()

    print("\n" + "─" * 55)
    print("  CODING BLACKWELL")
    print("  Zephyr is entering coding planning mode.")
    print("  Questions are focused on CS and software engineering.")
    print("  Type 'skip' to skip. 'done' to end early.")
    print("─" * 55 + "\n")

    if wm["sessions"] > 0:
        print(f"  Session #{wm['sessions'] + 1}  |  Skills: {len(wm['skills'])}  |  Patterns: {len(wm['patterns'])}\n")

    MAX_QUESTIONS = 5
    qa_pairs = []
    i = 0

    while i < MAX_QUESTIONS:
        i += 1
        # In TTY mode use \r so the "Generating…" spinner overwrites itself.
        # In pipe/GUI mode \r is not interpreted as overwrite, so use \n instead
        # to avoid the spinner appearing inline with the question in the console.
        if sys.stdout.isatty():
            print(f"  Generating question {i}/{MAX_QUESTIONS}...", end="\r", flush=True)
        else:
            print(f"  Generating question {i}/{MAX_QUESTIONS}...", flush=True)

        question = generate_next_coding_question(prior_qa=qa_pairs)

        # Clear the spinner line only in TTY mode (pipe mode already newlined above)
        if sys.stdout.isatty():
            print(" " * 40, end="\r", flush=True)

        print(f"  Zephyr [{i}/{MAX_QUESTIONS}]: {question}")
        print()

        try:
            _prompt = "  You: " if sys.stdout.isatty() else ""
            answer = ""
            for _retry in range(16):    # drain stray \n pipe-flush artifacts
                answer = input(_prompt).strip()
                if sys.stdout.isatty():
                    # TTY: drain Windows console buffer to stop paste residue
                    # from silently answering subsequent questions
                    _drain_console_buffer()
                if answer or sys.stdout.isatty():
                    break
                # Pipe/GUI mode: empty string = OS pipe flush artifact,
                # NOT the user pressing Enter on a blank line.  Retry.
        except (EOFError, KeyboardInterrupt):
            print("\n  Session interrupted.")
            break

        if answer.lower() == "done":
            break
        if answer.lower() == "skip":
            print("  (skipped)\n")
            i -= 1   # don't count skipped questions against the max
            continue
        if not answer:
            # Exhausted retries — still empty. Don't penalise the question
            # counter; just move on so the session isn't stuck.
            continue

        qa_pairs.append({"question": question, "answer": answer})

        # Write pair immediately — don't batch at end
        training_record = {
            "conversations": [
                {"from": "human", "value": question},
                {"from": "gpt",   "value": answer},
            ],
            "source": "blackwell_coding_session",
            "category": "coding",
        }
        with open(CODING_TRAINING_PATH, "a", encoding="utf-8") as f:
            f.write(json.dumps(training_record) + "\n")

        # Generate wiki page immediately
        try:
            from blackwell.wiki import write_wiki_page
            write_wiki_page(training_record)
        except Exception as _wiki_err:
            print(f"  [wiki] {_wiki_err}", flush=True)

        print(f"\n  Zephyr: Got it.\n")

    # Final drain: flush any paste residue that outlasted the session so it
    # doesn't leak into the main chat loop and trigger spurious LLM responses.
    _drain_console_buffer()

    if not qa_pairs:
        print("  No answers recorded. Session ended.\n")
        return []

    print("  Synthesising coding world model update...\n")
    update = synthesise_coding_update(qa_pairs)

    def _merge(existing: list, new: list, cap: int) -> list:
        """Append new items that aren't already present (case-insensitive), then cap."""
        seen = {x.lower().strip() for x in existing}
        for item in new:
            if item.lower().strip() not in seen:
                existing.append(item)
                seen.add(item.lower().strip())
        return existing[-cap:]   # keep most recent up to cap

    wm["skills"]   = _merge(wm["skills"],   update.get("skills",   []), cap=20)
    wm["patterns"] = _merge(wm["patterns"], update.get("patterns", []), cap=12)
    wm["gaps"]     = _merge(wm["gaps"],     update.get("gaps",     []), cap=8)
    wm["sessions"] += 1
    save_coding_world_model(wm)

    print("─" * 55)
    print("  CODING WORLD MODEL UPDATE")
    print("─" * 55)
    if update.get("skills"):
        print("\n  Skills recorded:")
        for s in update["skills"]:
            print(f"    + {s}")
    if update.get("patterns"):
        print("\n  Patterns noted:")
        for p in update["patterns"]:
            print(f"    ~ {p}")
    if update.get("gaps"):
        print("\n  Focus areas:")
        for g in update["gaps"]:
            print(f"    ? {g}")
    print(f"\n  Total sessions: {wm['sessions']}  |  Skills: {len(wm['skills'])}  |  Patterns: {len(wm['patterns'])}")
    print("─" * 55 + "\n")
    print("  ── Coding Blackwell complete. Normal chat resumed. ──\n")

    return qa_pairs


def get_coding_world_model_context() -> str:
    """Returns coding world model summary for injection into system prompt."""
    wm = load_coding_world_model()
    if not wm["skills"] and not wm["patterns"]:
        return ""
    parts = []
    if wm["skills"]:
        parts.append("User's coding stack: " + "; ".join(wm["skills"][-5:]))
    if wm["patterns"]:
        parts.append("Coding style: " + "; ".join(wm["patterns"][-5:]))
    if wm["gaps"]:
        parts.append("Learning goals: " + "; ".join(wm["gaps"][-3:]))
    return "\n".join(parts)
